package gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import constructor.SortableTable;
import scripts.DatabaseHandler;

/**
 *
 * @author rashidismayilzade
 */
public class GeneralLibraryForUsersFrame extends javax.swing.JPanel {

        /**
         * Creates new form PersonalLibraryFrame
         */
        public GeneralLibraryForUsersFrame() {
                initComponents();
                SortableTable.makeSortable(jTable1);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                searchField = new javax.swing.JTextField();
                searchButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                editButton = new javax.swing.JButton();
                navigationPanel = new javax.swing.JPanel();
                WelcomeText = new javax.swing.JLabel();
                setBackground(new java.awt.Color(44, 46, 67));

                searchField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchFieldActionPerformed(evt);
                        }
                });

                searchButton.setBackground(new java.awt.Color(204, 204, 204));
                searchButton.setText("Search");
                searchButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchButtonActionPerformed(evt);
                        }
                });
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title", "Author", "Review", "Score"
                                }));
                                editButton = new javax.swing.JButton();
                                editButton.setBackground(new java.awt.Color(204, 204, 204));
                                editButton.setText("Add Book to MyLibrary");
                                editButton.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        addToMyLibraryActionPerformed(evt);
                                    }
                                });
                                
  
                jScrollPane1.setViewportView(jTable1);

                editButton.setBackground(new java.awt.Color(204, 204, 204));
                editButton.setText("Add Book to MyLibrary");

                navigationPanel.setBackground(new java.awt.Color(89, 82, 96));

                WelcomeText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                WelcomeText.setForeground(new java.awt.Color(255, 213, 35));
                WelcomeText.setText("General Library");

                javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
                navigationPanel.setLayout(navigationPanelLayout);
                navigationPanelLayout.setHorizontalGroup(
                                navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(navigationPanelLayout.createSequentialGroup()
                                                                .addGap(167, 167, 167)
                                                                .addComponent(WelcomeText)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                navigationPanelLayout.setVerticalGroup(
                                navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(WelcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
                                                                Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                458,
                                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(29, 29, 29)
                                                                                                .addComponent(searchField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                221,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(searchButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                103,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(editButton,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                178,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(navigationPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                14,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(searchField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(searchButton))
                                                                .addGap(40, 40, 40)
                                                                .addComponent(editButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                201,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                DatabaseHandler HB = new DatabaseHandler();
                HB.populateTable(jTable1, "src\\csvfiles\\brodsky.csv");
        }// </editor-fold>

        // Starter
        public static void starter() {
                SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                                JFrame frame = new JFrame("General Library");
                                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                frame.getContentPane().add(new GeneralLibraryForUsersFrame());
                                frame.pack();
                                frame.setVisible(true);
                                frame.setLocationRelativeTo(null);

                        }

                });

        }

        private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {
                search();
        }

        private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
                search();
        }

        private void search() {
                String query = searchField.getText(); // Get the text from the search field
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Get the table model

                // Clear the table before populating it with search results
                model.setRowCount(0);

                // Populate the table with search results based on the query
                DatabaseHandler databaseHandler = new DatabaseHandler();
                databaseHandler.populateTable(jTable1, "src\\csvfiles\\brodsky.csv", query);
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel WelcomeText;
        private javax.swing.JButton editButton;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JPanel navigationPanel;
        private javax.swing.JButton searchButton;
        private javax.swing.JTextField searchField;
        // End of variables declaration

        private void addToMyLibraryActionPerformed(java.awt.event.ActionEvent evt) {
                // Get the selected row index
                int selectedRowIndex = jTable1.getSelectedRow();
            
                // Check if any row is selected
                if (selectedRowIndex != -1) {
                    // Get the selected row data
                    String title = jTable1.getValueAt(selectedRowIndex, 0).toString();
                    String author = jTable1.getValueAt(selectedRowIndex, 1).toString();
                    String review = "";
            
                    // Check if review data is available
                    Object reviewObj = jTable1.getValueAt(selectedRowIndex, 2);
                    if (reviewObj != null) {
                        review = reviewObj.toString();
                    }
            
                    // Append the selected row data to the PersonalDatabase.csv file
                    String filePath = "src\\csvfiles\\PersonalDatabse.csv";
                    DatabaseHandler databaseHandler = new DatabaseHandler();
                    databaseHandler.appendDataToFile(filePath, title + "," + author + "," + review);
            
                    // Optionally, you can notify the user that the book has been added to their library
                    // For example:
                    JOptionPane.showMessageDialog(this, "Book added to your library successfully.");
                } else {
                    // If no row is selected, show a message to the user
                    JOptionPane.showMessageDialog(this, "Please select a book to add to your library.");
                }
            }
            
            
            
}
