package gui;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author rashidismayilzade
 */
public class MainApplicationFrame extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainApplicationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        SignOutButton = new javax.swing.JButton();
        myBooksButton = new javax.swing.JButton();
        LibraryButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 46, 67));

        navigationPanel.setBackground(new java.awt.Color(89, 82, 96));

        WelcomeText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 213, 35));
        WelcomeText.setText("Welcome to our Application");

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeText)
                .addGap(124, 124, 124))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        SignOutButton.setBackground(new java.awt.Color(204, 204, 204));
        SignOutButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        SignOutButton.setText("Sign Out");

        myBooksButton.setBackground(new java.awt.Color(204, 204, 204));
        myBooksButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        myBooksButton.setText("My Books");
        myBooksButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalLibraryFrame.starter();
            }
        });

        LibraryButton.setBackground(new java.awt.Color(204, 204, 204));
        LibraryButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LibraryButton.setText("Library");
        LibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneralLibraryForUsersFrame.starter();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SignOutButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(LibraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LibraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(SignOutButton))
        );
    }// </editor-fold>                        
    
    //Starter
    public static void Starter(){
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Main Application");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new MainApplicationFrame());
                frame.pack();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

                                    

    // Variables declaration - do not modify                     
    private javax.swing.JButton LibraryButton;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JButton myBooksButton;
    private javax.swing.JPanel navigationPanel;
    // End of variables declaration                   
}
