package gui.admin;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import gui.loginPage.LoginFrame;

/**
 *
 * @author rashidismayilzade
 */
public class AdminMainApplicationFrame extends javax.swing.JPanel {

    /**
     * Creates new form AdminFrame
     */
    public AdminMainApplicationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        signOutButton = new javax.swing.JButton();
        navigationPanel = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        SignOutButton1 = new javax.swing.JButton();
        editLibraryButton = new javax.swing.JButton();

        signOutButton.setBackground(new java.awt.Color(204, 204, 204));
        signOutButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        signOutButton.setText("Sign Out");

        setBackground(new java.awt.Color(44, 46, 67));


        navigationPanel.setBackground(new java.awt.Color(89, 82, 96));

        WelcomeText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 213, 35));
        WelcomeText.setText("Welcome to our Application");

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(WelcomeText)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        SignOutButton1.setBackground(new java.awt.Color(204, 204, 204));
        SignOutButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        SignOutButton1.setText("Sign Out");

        editLibraryButton.setBackground(new java.awt.Color(204, 204, 204));
        editLibraryButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        editLibraryButton.setText("Edit General Library");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SignOutButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(editLibraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(editLibraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(SignOutButton1))
        );

        editLibraryButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Get the parent JFrame
                JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(AdminMainApplicationFrame.this);
                
                // Dispose the parent JFrame
                parentFrame.dispose();
                
                // Open the new AdminLibraryFrame
                AdminLibraryFrame.Starter();
            }
        });

        SignOutButton1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Get the parent JFrame
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(AdminMainApplicationFrame.this);

            // Dispose the parent JFrame
            parentFrame.dispose();

            // Open the login frame
            LoginFrame.starter();
        }
    });
        

    }// </editor-fold>                        

    
    //Starter
    public static void starter(){
    SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            JFrame frame = new JFrame("Admin Application");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.getContentPane().add(new AdminMainApplicationFrame());
            frame.pack();
            frame.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify                     
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton SignOutButton1;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JButton editLibraryButton;
    private javax.swing.JPanel navigationPanel;
    // End of variables declaration                   
}
